services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy

networks:
  proxy:
    external: true